# General
feature_cols:
- "Gender"
- "Age"
- "Driving_License"
- "Region_Code"
- "Previously_Insured"
- "Vehicle_Age"
- "Vehicle_Damage"
- "Annual_Premium"
- "Policy_Sales_Channel"
- "Vintage"
target_cols: "Response"

# Raw data
raw_data:
    path_train: "../data/raw/train.csv"
    path_test: "../data/raw/test.csv"
    id_column: "id"
    categorical_cols:
    - "Gender"
    - "Vehicle_Age"
    - "Vehicle_Damage"
    continuous_cols:
    - "Age"
    - "Region_Code"
    - "Annual_Premium"
    - "Policy_Sales_Channel"
    - "Vintage"